// Writes docs/PROOF.md: the test run and every factory verdict, generated from the repo so judges can check
// each number in the submission against its source. Run: node scripts/proof.mjs
import fs from "node:fs";
import { execSync } from "node:child_process";

let out = "";
try { out = execSync("node --test --test-force-exit --test-reporter=spec test/*.test.mjs 2>&1", { encoding: "utf8", timeout: 600000 }); } catch (e) { out = String(e.stdout); }
const tests = out.split("\n").filter((l) => /^[✔✖]/.test(l.trim())).map((l) => l.trim().replace(/ \([\d.]+ms\)$/, ""));
const passed = tests.filter((t) => t.startsWith("✔")).length;

const stats = fs.readFileSync("factory/stats.jsonl", "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l));
const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
const rows = stats.map((s) => {
  const h = s.harness?.at(-1) || {};
  const g = s.grades?.at(-1) || {};
  const why = s.verdict === "published" ? (g.flaws?.[0] ? `minor: ${g.flaws[0]}` : "") : (h.errors?.[0] || g.flaws?.[0] || s.error || "");
  return `| ${s.slug} | ${s.verdict} | ${s.grades?.length || 0} | ${h.renders ?? ""} | ${cell(why).slice(0, 220)} |`;
});
const pub = stats.filter((s) => s.verdict === "published").length;
const lessons = fs.readFileSync("factory/lessons.md", "utf8").split("\n").filter((l) => l.startsWith("- "));

const md = `# Proof

Generated by \`node scripts/proof.mjs\` on ${new Date().toISOString().slice(0, 10)} from the test run and
[\`factory/stats.jsonl\`](../factory/stats.jsonl). Nothing here is typed by hand.

## Tests: ${passed}/${tests.length} passing

${tests.map((t) => `- ${t}`).join("\n")}

The PayPal client is a fake in these tests (\`setPaypalClient\`), so they cover Oasis's own logic: pricing, the
capture race, amount checks, refunds, held royalties and webhooks. They do not prove the sandbox round trip.

## Factory v2 verdicts: ${pub} published, ${stats.length - pub} rejected of ${stats.length}

Every build is rendered across its knob space by the harness, then judged by a grader in a fresh session that
never saw the builder's reasoning. "Rounds" is how many grader passes it took (the builder may revise twice).

| Asset | Verdict | Rounds | Renders checked | Main finding |
|---|---|---|---|---|
${rows.join("\n")}

## Lessons the factory taught itself (${lessons.length})

Each verdict adds one general rule to every later build's prompt ([\`factory/lessons.md\`](../factory/lessons.md)).
The first five:

${lessons.slice(0, 5).join("\n")}
`;
fs.mkdirSync("docs", { recursive: true });
fs.writeFileSync("docs/PROOF.md", md);
console.log(`docs/PROOF.md: ${passed}/${tests.length} tests, ${stats.length} verdicts`);
